name: Contact form Cloud Function deploy
on:
  push:
    paths:
      - .github/workflows/contact-form-backend.yml
      - cloud-function/**
jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Authentication
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Deploy function
        uses: google-github-actions/deploy-cloud-function@v1
        with:
          name: send-mail
          runtime: nodejs18
          entry_point: send-mail
          memory_mb: 128
          source_dir: cloud-function
          min_instances: 0
          max_instances: 0
          region: europe_west1
