name: Get reviews endpoint deployment
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/get-reviews.yml
      - cloud-function/get-reviews/**
jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Authentication
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Deploy function
        id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: get-reviews
          runtime: nodejs20
          entry_point: getReviews
          memory_mb: 128
          source_dir: cloud-function/get-reviews
          min_instances: 0
          max_instances: 1
          region: europe-west1
