name: Reviews fetcher deployment
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/reviews-fetcher.yml
      - cloud-function/reviews-fetcher/**
jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Authentication
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Deploy function
        id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: fetch-reviews
          runtime: nodejs20
          entry_point: fetchReviews
          memory_mb: 128
          source_dir: cloud-function/reviews-fetcher
          min_instances: 0
          max_instances: 1
          region: europe-west1
          secret_environment_variables: GOOGLE_PLACES_KEY=${{ secrets.GOOGLE_PLACES_KEY }}
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/anne-avenel-site/topics/reviews
